# Generated by Django 2.2 on 2020-07-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_flag',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
