# Generated by Django 2.2 on 2020-06-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrinio_id', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('composite_ticker', models.CharField(max_length=255)),
                ('figi', models.CharField(max_length=255)),
                ('composite_figi', models.CharField(max_length=255)),
                ('share_class_figi', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
