# Generated by Django 2.2 on 2020-06-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('templates', models.CharField(max_length=45)),
                ('historical', models.CharField(max_length=1)),
                ('screenable', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
