# Generated by Django 2.2 on 2020-06-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0003_data_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_tag',
            name='text',
        ),
    ]
