# Generated by Django 2.2 on 2020-06-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0004_remove_data_tag_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_tag',
            old_name='type',
            new_name='grouping',
        ),
    ]
