# Generated by Django 2.2 on 2020-06-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0006_auto_20200630_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_retrieval_log',
            name='period',
            field=models.CharField(max_length=4),
        ),
    ]
