# Generated by Django 2.2 on 2020-06-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0007_auto_20200630_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical_retrieval_log',
            name='value',
        ),
        migrations.AddField(
            model_name='historical_retrieval_log',
            name='val_0',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historical_retrieval_log',
            name='val_1',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historical_retrieval_log',
            name='val_2',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historical_retrieval_log',
            name='val_3',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historical_retrieval_log',
            name='val_4',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historical_retrieval_log',
            name='val_5',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historical_retrieval_log',
            name='val_6',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historical_retrieval_log',
            name='val_7',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historical_retrieval_log',
            name='val_8',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
            preserve_default=False,
        ),
    ]
