# Generated by Django 2.2 on 2020-07-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0008_auto_20200630_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_tag',
            old_name='grouping',
            new_name='statement_code',
        ),
        migrations.RenameField(
            model_name='data_tag',
            old_name='templates',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='historical_retrieval_log',
            old_name='tag',
            new_name='data_tag',
        ),
        migrations.AddField(
            model_name='data_tag',
            name='balance',
            field=models.CharField(default='=', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_tag',
            name='factor',
            field=models.CharField(default='+', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_tag',
            name='intrinio_id',
            field=models.CharField(default='z', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_tag',
            name='nature',
            field=models.CharField(default='guess', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_tag',
            name='parent',
            field=models.CharField(default='data_tag', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_tag',
            name='sequence',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data_tag',
            name='tag',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='historical_retrieval_log',
            name='period',
            field=models.CharField(max_length=3),
        ),
    ]
