# Generated by Django 2.2 on 2020-07-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0009_auto_20200722_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_tag',
            name='historical',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='data_tag',
            name='screenable',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
