# Generated by Django 2.2.14 on 2020-08-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0010_auto_20200722_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_tag',
            name='nature',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='data_tag',
            name='parent',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='data_tag',
            name='template',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='data_tag',
            name='units',
            field=models.CharField(default='', max_length=255),
        ),
    ]
