# Generated by Django 2.2 on 2020-07-11 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0003_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist_cols',
            name='col_name',
        ),
        migrations.RemoveField(
            model_name='watchlist_cols',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='watchlist_cols',
            name='test',
        ),
        migrations.AddField(
            model_name='formula',
            name='col_name',
            field=models.CharField(default='Heading', max_length=255),
        ),
        migrations.AddField(
            model_name='watchlist_cols',
            name='formula_name',
            field=models.CharField(default='X', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_head',
            name='wpctd1',
            field=models.CharField(default='X', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_head',
            name='wpctd2',
            field=models.CharField(default='X', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_head',
            name='wpctd3',
            field=models.CharField(default='X', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_head',
            name='wpctd4',
            field=models.CharField(default='X', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_head',
            name='wpctd5',
            field=models.CharField(default='X', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_head',
            name='wvald1',
            field=models.CharField(default='X', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_head',
            name='wvald2',
            field=models.CharField(default='X', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_head',
            name='wvald3',
            field=models.CharField(default='X', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_head',
            name='wvald4',
            field=models.CharField(default='X', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_head',
            name='wvald5',
            field=models.CharField(default='X', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formula',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='userprofiles.User'),
        ),
        migrations.AlterField(
            model_name='user_ticker_tag_periods',
            name='period',
            field=models.CharField(choices=[('QTR0', 'Most Recent Quarter'), ('QTR1', '2nd Most Recent Quarter'), ('QTR2', '3rd Most Recent Quarter'), ('QTR3', '4th Most Recent Quarter'), ('QTR4', '5th Most Recent Quarter (12 Mos. Prior)'), ('QTR5', '6th Most Recent Quarter'), ('QTR6', '7th Most Recent Quarter'), ('QTR7', '8th Most Recent Quarter'), ('QTR8', '9th Most Recent Quarter (24 Mos. Prior)'), ('TTM0', 'Most Recent Trailing 12 Months'), ('TTM1', 'Trailing 12 Months, 1 Quarter Arrears'), ('TTM2', 'Trailing 12 Months, 2 Quarters Arrears'), ('TTM3', 'Trailing 12 Months, 3 Quarters Arrears'), ('TTM4', 'Trailing 12 Months, 1 Year in Arrears'), ('TTM5', 'Trailing 12 Months, 5 Quarters Arrears'), ('TTM6', 'Trailing 12 Months, 6 Quarters Arrears'), ('TTM7', 'Trailing 12 Months, 7 Quarters Arrears'), ('TTM8', 'Trailing 12 Months, 2 Years in Arrears')], default='QTR0', max_length=4),
        ),
        migrations.CreateModel(
            name='Watchlist_Rows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.FloatField(default=0)),
                ('ticker', models.CharField(max_length=255)),
                ('target', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tval_1', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tval_2', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tval_3', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tval_4', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tval_5', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tpct_1', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tpct_2', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tpct_3', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tpct_4', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tpct_5', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='watchlists.Watchlist_Head')),
            ],
        ),
    ]
