# Generated by Django 2.2 on 2020-07-11 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0005_auto_20200711_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist_cols',
            name='formula_name',
        ),
        migrations.AddField(
            model_name='watchlist_cols',
            name='formula',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='watchlists.Formula'),
            preserve_default=False,
        ),
    ]
