# Generated by Django 2.2 on 2020-07-20 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0006_auto_20200711_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist_cols',
            name='tag',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='watchlist_cols',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='watchlists.Formula'),
        ),
    ]
