# Generated by Django 2.2 on 2020-07-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0007_auto_20200720_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist_cols',
            name='period',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
