# Generated by Django 2.2 on 2020-07-20 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0008_watchlist_cols_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist_cols',
            name='formula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='watchlists.Formula'),
        ),
    ]
