# Generated by Django 2.2.14 on 2020-08-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0009_auto_20200720_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist_cols',
            name='col_heading',
            field=models.CharField(default='heading', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist_cols',
            name='col_tooltip',
            field=models.CharField(default='heading', max_length=255),
            preserve_default=False,
        ),
    ]
