# Generated by Django 2.2.14 on 2020-08-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0010_auto_20200806_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist_cols',
            old_name='col_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='watchlist_cols',
            old_name='col_tooltip',
            new_name='tooltip',
        ),
    ]
